In [ ]:
from  google.colab import drive  
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/econ4130
### save and load data using pickle
import pickle
def psave(dataframe, fname):
    with open('{}.pkl'.format(fname),'wb') as pickle_file:
        pickle.dump(dataframe,pickle_file)
        
def pload(fname):
  
  with open('{}.pkl'.format(fname),'rb') as pickle_file:
      dataframe=pickle.load(pickle_file)
      return dataframe

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/econ4130

In [ ]:
DF=pload('11_6')

In [ ]:
DF

              1M    2M    3M  ...  ROWFDNQ027S_pct  PAYEMS_pct    M2_pct
1999-01-04   NaN   NaN  4.49  ...              NaN         NaN       NaN
1999-01-05   NaN   NaN  4.48  ...         0.001679    0.000106  0.000143
1999-01-06   NaN   NaN  4.47  ...         0.001676    0.000106  0.000143
1999-01-07   NaN   NaN  4.44  ...         0.001673    0.000106  0.000143
1999-01-08   NaN   NaN  4.48  ...         0.001671    0.000106  0.000143
...          ...   ...   ...  ...              ...         ...       ...
2020-10-26  0.08  0.09  0.11  ...         0.000000    0.000000  0.000000
2020-10-27  0.08  0.09  0.10  ...         0.000000    0.000000  0.000000
2020-10-28  0.07  0.09  0.10  ...         0.000000    0.000000  0.000000
2020-10-29  0.08  0.10  0.09  ...         0.000000    0.000000  0.000000
2020-10-30  0.08  0.09  0.09  ...         0.000000    0.000000  0.000000

[5464 rows x 138 columns]

In [ ]:
###Generate technical indicators
od = DF.filter(['1Y','2Y','3Y','5Y','7Y','10Y','20Y','30Y'],axis=1)
print(od)

df_SMA_5= od.rolling(5).sum()/5
df_SMA_5=df_SMA_5.add_suffix('_SMA5')

              1Y    2Y    3Y    5Y    7Y   10Y   20Y   30Y
1999-01-04  4.58  4.58  4.57  4.57  4.75  4.69  5.42  5.15
1999-01-05  4.56  4.64  4.64  4.62  4.80  4.74  5.48  5.21
1999-01-06  4.53  4.62  4.62  4.61  4.76  4.73  5.42  5.17
1999-01-07  4.51  4.63  4.63  4.62  4.82  4.77  5.48  5.23
1999-01-08  4.57  4.71  4.71  4.72  4.92  4.86  5.57  5.26
...          ...   ...   ...   ...   ...   ...   ...   ...
2020-10-26  0.12  0.16  0.18  0.35  0.58  0.81  1.37  1.59
2020-10-27  0.12  0.16  0.19  0.34  0.56  0.79  1.34  1.57
2020-10-28  0.12  0.16  0.19  0.34  0.56  0.79  1.34  1.56
2020-10-29  0.12  0.16  0.20  0.38  0.61  0.85  1.39  1.62
2020-10-30  0.13  0.14  0.19  0.38  0.64  0.88  1.43  1.65

[5464 rows x 8 columns]

In [ ]:
df_SMA_5

            1Y_SMA5  2Y_SMA5  3Y_SMA5  ...  10Y_SMA5  20Y_SMA5  30Y_SMA5
1999-01-04      NaN      NaN      NaN  ...       NaN       NaN       NaN
1999-01-05      NaN      NaN      NaN  ...       NaN       NaN       NaN
1999-01-06      NaN      NaN      NaN  ...       NaN       NaN       NaN
1999-01-07      NaN      NaN      NaN  ...       NaN       NaN       NaN
1999-01-08    4.550    4.636    4.634  ...     4.758     5.474     5.204
...             ...      ...      ...  ...       ...       ...       ...
2020-10-26    0.126    0.156    0.198  ...     0.834     1.396     1.624
2020-10-27    0.124    0.160    0.198  ...     0.830     1.390     1.618
2020-10-28    0.122    0.164    0.196  ...     0.822     1.378     1.606
2020-10-29    0.120    0.164    0.194  ...     0.818     1.370     1.596
2020-10-30    0.122    0.156    0.190  ...     0.824     1.374     1.598

[5464 rows x 8 columns]

In [ ]:
###moving averages
#10-day MA
df_SMA_10_0= od.rolling(10).sum()/10
df_SMA_10=df_SMA_10_0.add_suffix('_SMA10')
#15-day MA
df_SMA_15= od.rolling(15).sum()/15
df_SMA_15=df_SMA_15.add_suffix('_SMA15')
#20-day MA
df_SMA_20= od.rolling(20).sum()/20
df_SMA_20=df_SMA_20.add_suffix('_SMA20')
#50-day MA
df_SMA_50= od.rolling(50).sum()/50
df_SMA_50=df_SMA_50.add_suffix('_SMA50')
#200-day MA
df_SMA_200= od.rolling(200).sum()/200
df_SMA_200=df_SMA_200.add_suffix('_SMA200')

df_SMA_4= od.rolling(4).sum()/4
df_SMA_14= od.rolling(14).sum()/14
df_SMA_24= od.rolling(24).sum()/24
df_SMA_35= od.rolling(35).sum()/35
df_SMA_48= od.rolling(48).sum()/48

In [ ]:
###moving average spreads
# 10-day MA minus 4-day MA
df_SMA10_4=df_SMA_10_0.subtract(df_SMA_4)
df_SMA10_4=df_SMA10_4.add_suffix('_SMA10_4')
df_SMA10_4.info()
# 24-day MA minus 14-day MA
df_SMA24_14=df_SMA_24.subtract(df_SMA_14)
df_SMA24_14=df_SMA24_14.add_suffix('_SMA24_14')
# 48-day MA minus 35-day MA
df_SMA48_35=df_SMA_48.subtract(df_SMA_35)
df_SMA48_35=df_SMA48_35.add_suffix('_SMA48_35')

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5464 entries, 1999-01-04 to 2020-10-30
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1Y_SMA10_4   5455 non-null   float64
 1   2Y_SMA10_4   5455 non-null   float64
 2   3Y_SMA10_4   5455 non-null   float64
 3   5Y_SMA10_4   5455 non-null   float64
 4   7Y_SMA10_4   5455 non-null   float64
 5   10Y_SMA10_4  5455 non-null   float64
 6   20Y_SMA10_4  5455 non-null   float64
 7   30Y_SMA10_4  5455 non-null   float64
dtypes: float64(8)
memory usage: 384.2 KB

In [ ]:
df_SMA = pd.concat([df_SMA_5,df_SMA_10,df_SMA_15,df_SMA_20,df_SMA_50,df_SMA_200,
                    df_SMA10_4,df_SMA24_14,df_SMA48_35],axis=1,sort=False)
psave(df_SMA,'SMA1_1')

In [ ]:
###manual inspection
df_SMA['1Y_SMA5']['2003-12-15':'2019-01-02']

2003-12-15    1.306
2003-12-16    1.292
2003-12-17    1.278
2003-12-18    1.272
2003-12-19    1.266
              ...
2018-12-26    2.620
2018-12-27    2.612
2018-12-28    2.598
2018-12-31    2.600
2019-01-02    2.598
Name: 1Y_SMA5, Length: 3767, dtype: float64

In [ ]:
DF['1Y']['2003-12-15':'2019-01-02']

2003-12-15    1.30
2003-12-16    1.28
2003-12-17    1.26
2003-12-18    1.24
2003-12-19    1.25
              ...
2018-12-26    2.61
2018-12-27    2.58
2018-12-28    2.57
2018-12-31    2.63
2019-01-02    2.60
Name: 1Y, Length: 3767, dtype: float64

In [ ]:
pload('SMA1_1').shape

(5464, 72)

In [ ]:
### Generate bond spread data
d=pload('11_6')
d['JGB1Y']

1999-01-04    0.567
1999-01-05    0.548
1999-01-06    0.519
1999-01-07    0.469
1999-01-08    0.516
              ...
2020-10-26   -0.126
2020-10-27   -0.135
2020-10-28   -0.136
2020-10-29   -0.137
2020-10-30   -0.138
Name: JGB1Y, Length: 5464, dtype: float64

In [ ]:
# US JAPAN BOND SPREAD
bdsp=pd.DataFrame()
for i in ['1Y','2Y','3Y','5Y','7Y','10Y','20Y','30Y']:
  name='USJPBDSP'+i
  jp='JGB'+i
  bdsp[name]=d[i]-d[jp]

In [ ]:
bdsp

            USJPBDSP1Y  USJPBDSP2Y  ...  USJPBDSP20Y  USJPBDSP30Y
1999-01-04       4.013       3.790  ...        2.736          NaN
1999-01-05       4.012       3.882  ...        2.837          NaN
1999-01-06       4.011       3.904  ...        2.851          NaN
1999-01-07       4.041       3.997  ...        3.070          NaN
1999-01-08       4.054       4.002  ...        3.055          NaN
...                ...         ...  ...          ...          ...
2020-10-26       0.246       0.293  ...        0.962        0.951
2020-10-27       0.255       0.290  ...        0.932        0.940
2020-10-28       0.256       0.290  ...        0.932        0.930
2020-10-29       0.257       0.290  ...        0.983        0.994
2020-10-30       0.268       0.265  ...        1.013        1.010

[5464 rows x 8 columns]

In [ ]:
#US EU BOND SPREAD
for i in ['2Y','5Y','7Y','10Y','3Y']:
  name='USEUBDSP'+i
  jp='ECB'+i
  bdsp[name]=d[i]-d[jp]

In [ ]:
bdsp

            USJPBDSP1Y  USJPBDSP2Y  ...  USEUBDSP10Y  USEUBDSP3Y
1999-01-04       4.013       3.790  ...          NaN         NaN
1999-01-05       4.012       3.882  ...          NaN         NaN
1999-01-06       4.011       3.904  ...          NaN         NaN
1999-01-07       4.041       3.997  ...          NaN         NaN
1999-01-08       4.054       4.002  ...          NaN         NaN
...                ...         ...  ...          ...         ...
2020-10-26       0.246       0.293  ...       0.6869      0.6043
2020-10-27       0.255       0.290  ...       0.6669      0.6143
2020-10-28       0.256       0.290  ...       0.6669      0.6143
2020-10-29       0.257       0.290  ...       0.7269      0.6243
2020-10-30       0.268       0.265  ...       0.7569      0.6143

[5464 rows x 13 columns]

In [ ]:
###US intra-market (Different time to maturity) bond spread
l=['1Y','2Y','3Y','5Y','7Y','10Y','20Y','30Y']
for i in range(len(l)):
  ii=l[i]
  a=l[i+1:]
  for j in a:
    name= 'US'+ii+'-'+j
    bdsp[name]=d[ii]-d[j]
bdsp

            USJPBDSP1Y  USJPBDSP2Y  USJPBDSP3Y  ...  US10Y-20Y  US10Y-30Y  US20Y-30Y
1999-01-04       4.013       3.790       3.503  ...      -0.73      -0.46       0.27
1999-01-05       4.012       3.882       3.615  ...      -0.74      -0.47       0.27
1999-01-06       4.011       3.904       3.669  ...      -0.69      -0.44       0.25
1999-01-07       4.041       3.997       3.813  ...      -0.71      -0.46       0.25
1999-01-08       4.054       4.002       3.785  ...      -0.71      -0.40       0.31
...                ...         ...         ...  ...        ...        ...        ...
2020-10-26       0.246       0.293       0.314  ...      -0.56      -0.78      -0.22
2020-10-27       0.255       0.290       0.325  ...      -0.55      -0.78      -0.23
2020-10-28       0.256       0.290       0.325  ...      -0.55      -0.77      -0.22
2020-10-29       0.257       0.290       0.339  ...      -0.54      -0.77      -0.23
2020-10-30       0.268       0.265       0.321  ...      -0.55      -0.77      -0.22

[5464 rows x 41 columns]

In [ ]:

l=['2Y','5Y','7Y','10Y','3Y']
for i in range(len(l)):
  l[i]='ECB'+l[i]
l

['ECB2Y', 'ECB5Y', 'ECB7Y', 'ECB10Y', 'ECB3Y']

In [ ]:
### EU intra-market (Different time to maturity) bond spread
for i in range(len(l)):
  ii=l[i]
  a=l[i+1:]
  for j in a:
    name= ii+'-'+j
    bdsp[name]=d[ii]-d[j]
bdsp

            USJPBDSP1Y  USJPBDSP2Y  ...  USECB7Y-ECB3Y  USECB10Y-ECB3Y
1999-01-04       4.013       3.790  ...            NaN             NaN
1999-01-05       4.012       3.882  ...            NaN             NaN
1999-01-06       4.011       3.904  ...            NaN             NaN
1999-01-07       4.041       3.997  ...            NaN             NaN
1999-01-08       4.054       4.002  ...            NaN             NaN
...                ...         ...  ...            ...             ...
2020-10-26       0.246       0.293  ...         0.3569          0.5474
2020-10-27       0.255       0.290  ...         0.3569          0.5474
2020-10-28       0.256       0.290  ...         0.3569          0.5474
2020-10-29       0.257       0.290  ...         0.3569          0.5474
2020-10-30       0.268       0.265  ...         0.3569          0.5474

[5464 rows x 51 columns]

In [ ]:
##save bond spread data
psave(bdsp,'bdsp')